package model;

/**
 * Error codes for Employment Contract business operations.
 */
public enum ContractErrorCode {
    OVERLAP_DETECTED,
    INVALID_EFFECTIVE_DATE,
    INVALID_END_DATE,
    INVALID_CONTRACT_STATUS,
    CONTRACT_NOT_FOUND,
    EMPLOYEE_NOT_FOUND,
    DATA_INTEGRITY_VIOLATION,
    DATABASE_ERROR,
    INVALID_CONTRACT_TYPE,
    CONTRACT_NOT_EDITABLE,
    INVALID_TERMINATION_DATE
}

