version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hrm_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nguyenlebinhank63CBH 
      - MYSQL_DATABASE=hrm
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pnguyenlebinhank63CBH"] 
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrm-app    
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy 
    environment:
      - DB_URL=jdbc:mysql://db:3306/hrm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
      - DB_USERNAME=root
      - DB_PASSWORD=nguyenlebinhank63CBH

volumes:
  mysql-data: